# Generated by Django 3.1.7 on 2021-04-16 18:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_field_model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('suffix_form', models.CharField(blank=True, max_length=200, null=True)),
                ('prefix_form', models.CharField(blank=True, max_length=200, null=True)),
                ('Home_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('work_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('Social_security_num', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('address_city', models.CharField(blank=True, max_length=200, null=True)),
                ('address_state', models.CharField(blank=True, max_length=200, null=True)),
                ('address_zip', models.IntegerField(blank=True, null=True)),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_date', models.DateTimeField(blank=True, null=True)),
                ('employee_signature', models.FileField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='primerx_field_model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prime_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_lst_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_suffix_form', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_prefix_form', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_work_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('prime_Social_security_num', models.IntegerField(blank=True, null=True)),
                ('prime_education', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_address_city', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_address_state', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('prime_emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_emergency_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('prime_sex', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
