# Generated by Django 3.1.7 on 2021-04-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210417_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_model',
            old_name='date_of_date',
            new_name='date_of_birth',
        ),
    ]
