# Generated by Django 3.1.7 on 2021-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210417_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_address_model',
            old_name='address_city',
            new_name='prime_address_city',
        ),
        migrations.RenameField(
            model_name='patient_address_model',
            old_name='address_state',
            new_name='prime_address_state',
        ),
        migrations.RenameField(
            model_name='patient_address_model',
            old_name='address_street',
            new_name='prime_address_street',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='Social_security_num',
            new_name='prime_Social_security_num',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='education',
            new_name='prime_education',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='emergency_name',
            new_name='prime_emergency_name',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='emergency_phone',
            new_name='prime_emergency_phone',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='emergency_relation',
            new_name='prime_emergency_relation',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='first_name',
            new_name='prime_first_name',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='lst_name',
            new_name='prime_lst_name',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='middle_name',
            new_name='prime_middle_name',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='prefix_form',
            new_name='prime_prefix_form',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='sex',
            new_name='prime_sex',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='suffix_form',
            new_name='prime_suffix_form',
        ),
        migrations.RenameField(
            model_name='patient_model',
            old_name='work_number',
            new_name='prime_work_number',
        ),
        migrations.AddField(
            model_name='patient_address_model',
            name='prime_address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_model',
            name='prime_patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
